/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    companies: Company;
    users: User;
    media: Media;
    'image-choice-assessments': ImageChoiceAssessment;
    'content-rank': ContentRank;
    'questions-bank': QuestionsBank;
    'migration-review-sessions': MigrationReviewSession;
    'platform-survey-questions': PlatformSurveyQuestion;
    'platform-survey-responses': PlatformSurveyResponse;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'image-choice-assessments': ImageChoiceAssessmentsSelect<false> | ImageChoiceAssessmentsSelect<true>;
    'content-rank': ContentRankSelect<false> | ContentRankSelect<true>;
    'questions-bank': QuestionsBankSelect<false> | QuestionsBankSelect<true>;
    'migration-review-sessions': MigrationReviewSessionsSelect<false> | MigrationReviewSessionsSelect<true>;
    'platform-survey-questions': PlatformSurveyQuestionsSelect<false> | PlatformSurveyQuestionsSelect<true>;
    'platform-survey-responses': PlatformSurveyResponsesSelect<false> | PlatformSurveyResponsesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  /**
   * Company name
   */
  name: string;
  /**
   * When enabled, this company is assigned the Platform Fit Quiz. Users can take the survey via a link with ?company=<this company id>. The company name is shown as the survey title.
   */
  platformSurveyEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * User's first name
   */
  firstName: string;
  /**
   * User's last name
   */
  lastName: string;
  /**
   * User's role in the system
   */
  userType: 'admin' | 'client-user';
  /**
   * The company this user belongs to
   */
  company: string | Company;
  /**
   * Image choice assessments (and other apps) this user can access. Only admins can edit.
   */
  assignedApplications?: (string | ImageChoiceAssessment)[] | null;
  /**
   * Whether this user account is active
   */
  isActive?: boolean | null;
  /**
   * Last time user logged in
   */
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-choice-assessments".
 */
export interface ImageChoiceAssessment {
  id: string;
  /**
   * Name of this image choice assessment
   */
  title: string;
  /**
   * Optional description of the assessment
   */
  description?: string | null;
  /**
   * Pairs of images for users to choose between
   */
  imagePairs: {
    /**
     * Optional label for this pair (e.g., "Brand A vs Brand B")
     */
    pairTitle?: string | null;
    /**
     * Left image option
     */
    imageLeft: string | Media;
    /**
     * Right image option
     */
    imageRight: string | Media;
    /**
     * Optional question to display with this pair
     */
    question?: string | null;
    id?: string | null;
  }[];
  /**
   * Time in seconds for each image pair
   */
  duration: number;
  /**
   * Whether this assessment is currently active
   */
  isActive?: boolean | null;
  /**
   * Instructions shown to users before starting
   */
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alt text for the image
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-rank".
 */
export interface ContentRank {
  id: string;
  /**
   * Name of this content rank instance
   */
  title: string;
  /**
   * ScreamingFrog crawl export (CSV)
   */
  screamingFrogCsv: string | Media;
  /**
   * GA4 report export (CSV)
   */
  ga4Csv: string | Media;
  /**
   * Company this content rank is assigned to
   */
  company: string | Company;
  /**
   * Whether this instance is active
   */
  isActive?: boolean | null;
  /**
   * Token for the Content Rank app to fetch this instance (without CMS login)
   */
  accessToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable fill-in-the-blank prompts (questions bank). Use _____ or [blank] for the gap. Admins can select these when building a Fill in the Blank activity.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions-bank".
 */
export interface QuestionsBank {
  id: string;
  /**
   * The sentence with a blank. Use _____ or [blank] where the user fills in the answer.
   */
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Content Migration Analyzer review sessions tied to email
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-review-sessions".
 */
export interface MigrationReviewSession {
  id: string;
  /**
   * Email address for this review session
   */
  email: string;
  /**
   * Unique session ID (used to resume session)
   */
  sessionId: string;
  /**
   * Migration data version (e.g. FINAL, v2)
   */
  dataVersion?: string | null;
  /**
   * Saved decisions: groupKey -> { client_decision, notes }
   */
  decisions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Platform Fit Quiz questions. Ordered by section then order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-survey-questions".
 */
export interface PlatformSurveyQuestion {
  id: string;
  /**
   * Section this question belongs to. Section labels are fixed; editors can only add questions to existing sections.
   */
  section:
    | 'content-complexity'
    | 'editor-autonomy'
    | 'marketing-personalization'
    | 'integration-ecosystem'
    | 'team-resources'
    | 'scale-performance'
    | 'budget-timeline'
    | 'future-vision'
    | 'day-in-the-life'
    | 'workflow-builder'
    | 'who-does-what'
    | 'current-platform'
    | 'future-state-wishlist';
  /**
   * Used for list ordering (section order, then order within section).
   */
  sectionSortOrder: number;
  /**
   * Sort order within the section
   */
  order: number;
  /**
   * Choose the question type first. The form will show only the fields needed for this type.
   */
  inputType:
    | 'multi-select'
    | 'single-select'
    | 'rating-scale'
    | 'ranking'
    | 'text-input'
    | 'pain-level-with-meta'
    | 'matrix';
  /**
   * Slug-style identifier (e.g. content-types, technical-comfort)
   */
  questionKey: string;
  /**
   * The question text
   */
  questionText: string;
  /**
   * Optional subtitle/clarifying copy under the question
   */
  helpText?: string | null;
  /**
   * Choices (multi/single-select, ranking) or row labels (matrix). Use hasTextInput for "Other, describe: ___".
   */
  options?:
    | {
        label: string;
        value: string;
        hasTextInput?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Column labels for the matrix (one selection per row).
   */
  columns?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Minimum value (e.g. 1).
   */
  ratingMin?: number | null;
  /**
   * Maximum value (e.g. 5).
   */
  ratingMax?: number | null;
  /**
   * Labels at the low and high end of the scale.
   */
  ratingLabels?: {
    minLabel?: string | null;
    maxLabel?: string | null;
  };
  /**
   * Whether the question must be answered
   */
  required?: boolean | null;
  /**
   * Hide question without deleting
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Platform Fit Quiz submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-survey-responses".
 */
export interface PlatformSurveyResponse {
  id: string;
  /**
   * Company this response belongs to, when the survey was taken via ?company= link.
   */
  company?: (string | null) | Company;
  /**
   * When the response was submitted
   */
  submittedAt: string;
  /**
   * Optional respondent info
   */
  respondent?: {
    name?: string | null;
    email?: string | null;
    company?: string | null;
  };
  /**
   * Full questionKey → value answer map
   */
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Time from start to submit in seconds
   */
  completionTime?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'image-choice-assessments';
        value: string | ImageChoiceAssessment;
      } | null)
    | ({
        relationTo: 'content-rank';
        value: string | ContentRank;
      } | null)
    | ({
        relationTo: 'questions-bank';
        value: string | QuestionsBank;
      } | null)
    | ({
        relationTo: 'migration-review-sessions';
        value: string | MigrationReviewSession;
      } | null)
    | ({
        relationTo: 'platform-survey-questions';
        value: string | PlatformSurveyQuestion;
      } | null)
    | ({
        relationTo: 'platform-survey-responses';
        value: string | PlatformSurveyResponse;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  platformSurveyEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  userType?: T;
  company?: T;
  assignedApplications?: T;
  isActive?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-choice-assessments_select".
 */
export interface ImageChoiceAssessmentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  imagePairs?:
    | T
    | {
        pairTitle?: T;
        imageLeft?: T;
        imageRight?: T;
        question?: T;
        id?: T;
      };
  duration?: T;
  isActive?: T;
  instructions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-rank_select".
 */
export interface ContentRankSelect<T extends boolean = true> {
  title?: T;
  screamingFrogCsv?: T;
  ga4Csv?: T;
  company?: T;
  isActive?: T;
  accessToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions-bank_select".
 */
export interface QuestionsBankSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-review-sessions_select".
 */
export interface MigrationReviewSessionsSelect<T extends boolean = true> {
  email?: T;
  sessionId?: T;
  dataVersion?: T;
  decisions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-survey-questions_select".
 */
export interface PlatformSurveyQuestionsSelect<T extends boolean = true> {
  section?: T;
  sectionSortOrder?: T;
  order?: T;
  inputType?: T;
  questionKey?: T;
  questionText?: T;
  helpText?: T;
  options?:
    | T
    | {
        label?: T;
        value?: T;
        hasTextInput?: T;
        id?: T;
      };
  columns?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  ratingMin?: T;
  ratingMax?: T;
  ratingLabels?:
    | T
    | {
        minLabel?: T;
        maxLabel?: T;
      };
  required?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-survey-responses_select".
 */
export interface PlatformSurveyResponsesSelect<T extends boolean = true> {
  company?: T;
  submittedAt?: T;
  respondent?:
    | T
    | {
        name?: T;
        email?: T;
        company?: T;
      };
  answers?: T;
  completionTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}