/**
 * Seed data for Platform Fit Quiz (platform-survey-questions).
 * From: 26_0129_PitchLab.pdf — Platform Fit Quiz.
 * Run from apps/cms: pnpm run seed:platform-survey
 */
type QuestionSeed = {
  section: string
  order: number
  questionKey: string
  questionText: string
  helpText?: string
  inputType: string
  options?: Array<{ label: string; value: string; hasTextInput?: boolean }>
  columns?: Array<{ label: string; value: string }>
  ratingMin?: number
  ratingMax?: number
  ratingLabels?: { minLabel?: string; maxLabel?: string }
  required?: boolean
  isActive?: boolean
}

export const platformSurveyQuestionsSeed: QuestionSeed[] = [
  // --- Section 1: Content Complexity ---
  {
    section: 'content-complexity',
    order: 0,
    questionKey: 'content-types',
    questionText: 'Beyond standard pages, what types of content do you regularly publish?',
    helpText: 'Select all that apply.',
    inputType: 'multi-select',
    options: [
      { label: 'Blog/articles', value: 'blog-articles' },
      { label: 'Case studies/portfolio', value: 'case-studies-portfolio' },
      { label: 'Products/services (structured catalogs)', value: 'products-services' },
      { label: 'Events', value: 'events' },
      { label: 'Resources/downloads', value: 'resources-downloads' },
      { label: 'Team/people profiles', value: 'team-people-profiles' },
      { label: 'Locations', value: 'locations' },
      { label: 'Custom content types', value: 'custom', hasTextInput: true },
    ],
  },
  {
    section: 'content-complexity',
    order: 1,
    questionKey: 'content-relationships',
    questionText: 'How connected is your content?',
    inputType: 'single-select',
    options: [
      { label: 'Mostly standalone pages', value: 'standalone' },
      { label: 'Some connections (e.g., articles tagged by topic)', value: 'some-connections' },
      { label: 'Highly connected (e.g., projects link to services, team members, case studies)', value: 'highly-connected' },
      { label: 'Complex relationships we need to visualize/filter', value: 'complex-relationships' },
    ],
  },
  {
    section: 'content-complexity',
    order: 2,
    questionKey: 'multilingual-multisite',
    questionText: 'Do you need to manage:',
    helpText: 'Select all that apply.',
    inputType: 'multi-select',
    options: [
      { label: 'Multiple languages', value: 'multiple-languages' },
      { label: 'Multiple brands/sites from one system', value: 'multiple-brands-sites' },
      { label: 'Regional variations of content', value: 'regional-variations' },
      { label: 'None of the above', value: 'none' },
    ],
  },
  // --- Section 2: Editor Autonomy & Experience ---
  {
    section: 'editor-autonomy',
    order: 0,
    questionKey: 'technical-comfort-level',
    questionText: 'The people updating the site most often are:',
    inputType: 'single-select',
    options: [
      { label: 'Very technical (comfortable with code, APIs)', value: 'very-technical' },
      { label: 'Moderately technical (can learn tools, follow documentation)', value: 'moderately-technical' },
      { label: 'Marketing/content folks (need intuitive interfaces)', value: 'marketing-content' },
      { label: 'Mix of all the above', value: 'mix' },
    ],
  },
  {
    section: 'editor-autonomy',
    order: 1,
    questionKey: 'design-freedom-vs-guardrails',
    questionText: 'When creating new pages, editors should:',
    inputType: 'single-select',
    options: [
      { label: 'Work within strict templates (brand consistency is critical)', value: 'strict-templates' },
      { label: 'Have flexible page builder with pre-approved components', value: 'flexible-page-builder' },
      { label: 'Have complete design freedom', value: 'complete-freedom' },
      { label: 'Different needs for different user types', value: 'different-needs' },
    ],
  },
  {
    section: 'editor-autonomy',
    order: 2,
    questionKey: 'three-am-edit-test',
    questionText: 'Your CEO calls at 11pm: "We need to update the homepage hero by morning." This scenario is:',
    inputType: 'single-select',
    options: [
      { label: 'Totally normal - happens monthly', value: 'totally-normal' },
      { label: 'Occasional - happens a few times a year', value: 'occasional' },
      { label: 'Rare emergency only', value: 'rare-emergency' },
      { label: 'Would never happen - we plan changes', value: 'would-never-happen' },
    ],
  },
  // --- Section 3: Marketing & Personalization ---
  {
    section: 'marketing-personalization',
    order: 0,
    questionKey: 'marketing-dynamic-content',
    questionText: 'Rate the importance: Dynamic content based on visitor behavior.',
    helpText: '1 = not important, 5 = critical',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: 'Not important', maxLabel: 'Critical' },
  },
  {
    section: 'marketing-personalization',
    order: 1,
    questionKey: 'marketing-ab-testing',
    questionText: 'Rate the importance: A/B testing built-in.',
    helpText: '1 = not important, 5 = critical',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: 'Not important', maxLabel: 'Critical' },
  },
  {
    section: 'marketing-personalization',
    order: 2,
    questionKey: 'marketing-form-sequences',
    questionText: 'Rate the importance: Form submissions trigger automated sequences.',
    helpText: '1 = not important, 5 = critical',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: 'Not important', maxLabel: 'Critical' },
  },
  {
    section: 'marketing-personalization',
    order: 3,
    questionKey: 'marketing-track-crm',
    questionText: 'Rate the importance: Track content engagement → CRM.',
    helpText: '1 = not important, 5 = critical',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: 'Not important', maxLabel: 'Critical' },
  },
  {
    section: 'marketing-personalization',
    order: 4,
    questionKey: 'marketing-personalized-experiences',
    questionText: 'Rate the importance: Personalized experiences for different segments.',
    helpText: '1 = not important, 5 = critical',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: 'Not important', maxLabel: 'Critical' },
  },
  {
    section: 'marketing-personalization',
    order: 5,
    questionKey: 'lead-generation-priority',
    questionText: "The website's primary job is:",
    inputType: 'single-select',
    options: [
      { label: 'Generate and qualify leads (forms, CTAs, tracking critical)', value: 'lead-gen' },
      { label: 'Support sales but not primary lead gen', value: 'support-sales' },
      { label: 'Brand/information focused', value: 'brand-info' },
      { label: 'E-commerce/transactions', value: 'ecommerce' },
    ],
  },
  // --- Section 4: Integration Ecosystem ---
  {
    section: 'integration-ecosystem',
    order: 0,
    questionKey: 'current-planned-integrations',
    questionText: 'Select your critical integrations:',
    helpText: 'Select all that apply.',
    inputType: 'multi-select',
    options: [
      { label: 'CRM', value: 'crm', hasTextInput: true },
      { label: 'Marketing automation (Marketo, Pardot, etc.)', value: 'marketing-automation' },
      { label: 'E-commerce platform', value: 'ecommerce-platform' },
      { label: 'DAM (Digital Asset Management)', value: 'dam' },
      { label: 'Analytics beyond Google Analytics', value: 'analytics-beyond-ga' },
      { label: 'Custom internal systems/APIs', value: 'custom-systems' },
      { label: 'Social media management', value: 'social-media' },
      { label: 'Customer support tools', value: 'customer-support' },
      { label: 'Other', value: 'other', hasTextInput: true },
    ],
  },
  {
    section: 'integration-ecosystem',
    order: 1,
    questionKey: 'integration-priority',
    questionText: 'When integrations break or need updating, we need:',
    inputType: 'single-select',
    options: [
      { label: 'Native, maintained integrations (we don\'t have dev resources)', value: 'native-maintained' },
      { label: 'API access is fine (we have developers)', value: 'api-access' },
      { label: 'Mix - some native, some we\'ll build', value: 'mix' },
      { label: "We'll build middleware if needed", value: 'build-middleware' },
    ],
  },
  // --- Section 5: Team & Resources ---
  {
    section: 'team-resources',
    order: 0,
    questionKey: 'development-resources',
    questionText: 'For ongoing website work, we have:',
    inputType: 'single-select',
    options: [
      { label: 'Full-time internal developers', value: 'fulltime-internal' },
      { label: 'Retainer with agency/freelancers', value: 'retainer-agency' },
      { label: 'Ad-hoc developer help when needed', value: 'ad-hoc' },
      { label: 'No developer access - must be self-service', value: 'no-developer' },
      { label: 'Not sure yet', value: 'not-sure' },
    ],
  },
  {
    section: 'team-resources',
    order: 1,
    questionKey: 'infrastructure-preferences',
    questionText: 'For hosting and infrastructure, we prefer:',
    inputType: 'single-select',
    options: [
      { label: 'Fully managed/hosted (we never think about servers)', value: 'fully-managed' },
      { label: 'Managed with some control (staging environments, etc.)', value: 'managed-some-control' },
      { label: 'We manage our own infrastructure', value: 'we-manage' },
      { label: 'Must be on our servers/cloud environment', value: 'our-servers' },
    ],
  },
  // --- Section 6: Scale & Performance ---
  {
    section: 'scale-performance',
    order: 0,
    questionKey: 'content-volume',
    questionText: 'We currently have / expect to have:',
    inputType: 'single-select',
    options: [
      { label: '< 100 pages', value: 'under-100' },
      { label: '100-500 pages', value: '100-500' },
      { label: '500-2,000 pages', value: '500-2000' },
      { label: '2,000-10,000 pages', value: '2000-10000' },
      { label: '10,000+ pages', value: '10000-plus' },
    ],
  },
  {
    section: 'scale-performance',
    order: 1,
    questionKey: 'traffic-performance',
    questionText: 'Monthly visitors are / will be:',
    inputType: 'single-select',
    options: [
      { label: '< 10K', value: 'under-10k' },
      { label: '10K-100K', value: '10k-100k' },
      { label: '100K-1M', value: '100k-1m' },
      { label: '1M+', value: '1m-plus' },
      { label: 'Highly variable (traffic spikes common)', value: 'highly-variable' },
    ],
  },
  // --- Section 7: Budget & Timeline ---
  {
    section: 'budget-timeline',
    order: 0,
    questionKey: 'platform-budget-annual',
    questionText: 'For platform licensing/hosting, we can spend:',
    inputType: 'single-select',
    options: [
      { label: '< $2,000/year', value: 'under-2k' },
      { label: '$2,000-$10,000/year', value: '2k-10k' },
      { label: '$10,000-$50,000/year', value: '10k-50k' },
      { label: '$50,000+/year', value: '50k-plus' },
      { label: 'Not sure / depends on value', value: 'not-sure' },
    ],
  },
  {
    section: 'budget-timeline',
    order: 1,
    questionKey: 'launch-urgency',
    questionText: 'We need to launch:',
    inputType: 'single-select',
    options: [
      { label: 'In 1-2 months (fast)', value: '1-2-months' },
      { label: 'In 3-6 months (standard)', value: '3-6-months' },
      { label: 'In 6-12 months (deliberate)', value: '6-12-months' },
      { label: '12+ months or phased rollout', value: '12-plus-months' },
    ],
  },
  // --- Section 8: Future Vision ---
  {
    section: 'future-vision',
    order: 0,
    questionKey: 'expected-evolution',
    questionText: 'In 2-3 years, we expect this site to:',
    helpText: 'Select all that apply.',
    inputType: 'multi-select',
    options: [
      { label: 'Grow significantly in content/traffic', value: 'grow-significantly' },
      { label: 'Add e-commerce capabilities', value: 'add-ecommerce' },
      { label: 'Become a platform (user accounts, dashboards, etc.)', value: 'become-platform' },
      { label: 'Support mobile app with same content', value: 'support-mobile-app' },
      { label: 'Feed content to multiple channels (email, social, etc.)', value: 'feed-multiple-channels' },
      { label: 'Stay roughly the same as today', value: 'stay-same' },
    ],
  },
  // --- Part 2: A Day in the Life (pain-level-with-meta) ---
  {
    section: 'day-in-the-life',
    order: 0,
    questionKey: 'scenario-1-service-pricing',
    questionText: 'Update a service page with new pricing',
    helpText: 'Rate pain level (1-5), frequency, who does it, and what makes it hard.',
    inputType: 'pain-level-with-meta',
  },
  {
    section: 'day-in-the-life',
    order: 1,
    questionKey: 'scenario-2-blog-embedded-video',
    questionText: 'Create a new blog post with embedded video',
    helpText: 'Rate pain level (1-5), frequency, who does it, and what makes it hard.',
    inputType: 'pain-level-with-meta',
  },
  {
    section: 'day-in-the-life',
    order: 2,
    questionKey: 'scenario-3-duplicate-case-study',
    questionText: "Duplicate last month's case study as a template",
    helpText: 'Rate pain level (1-5), frequency, who does it, and what makes it hard.',
    inputType: 'pain-level-with-meta',
  },
  {
    section: 'day-in-the-life',
    order: 3,
    questionKey: 'scenario-4-update-team-bios',
    questionText: 'Update team bios after someone leaves',
    helpText: 'Rate pain level (1-5), frequency, who does it, and what makes it hard.',
    inputType: 'pain-level-with-meta',
  },
  {
    section: 'day-in-the-life',
    order: 4,
    questionKey: 'scenario-5-landing-page-eod',
    questionText: 'Create a landing page for a campaign by EOD',
    helpText: 'Rate pain level (1-5), frequency, who does it, and what makes it hard.',
    inputType: 'pain-level-with-meta',
  },
  {
    section: 'day-in-the-life',
    order: 5,
    questionKey: 'scenario-6-preview-draft',
    questionText: 'Preview a draft before it goes live',
    helpText: 'Rate pain level (1-5), frequency, who does it, and what makes it hard.',
    inputType: 'pain-level-with-meta',
  },
  {
    section: 'day-in-the-life',
    order: 6,
    questionKey: 'scenario-7-update-footer',
    questionText: 'Update the footer across all pages',
    helpText: 'Rate pain level (1-5), frequency, who does it, and what makes it hard.',
    inputType: 'pain-level-with-meta',
  },
  {
    section: 'day-in-the-life',
    order: 7,
    questionKey: 'scenario-8-add-form-pages',
    questionText: 'Add a new form to 3 different pages',
    helpText: 'Rate pain level (1-5), frequency, who does it, and what makes it hard.',
    inputType: 'pain-level-with-meta',
  },
  // --- Build Your Ideal Workflow (ranking) ---
  {
    section: 'workflow-builder',
    order: 0,
    questionKey: 'ideal-workflow-ranking',
    questionText: 'When creating a new landing page, rank these in order of importance (1 = most important).',
    inputType: 'ranking',
    options: [
      { label: 'Start from a template library', value: 'template-library' },
      { label: 'Drag and drop pre-built sections', value: 'drag-drop-sections' },
      { label: 'Write custom code if needed', value: 'custom-code' },
      { label: 'See exactly how it looks as you build', value: 'see-as-you-build' },
      { label: 'Preview on different devices easily', value: 'preview-devices' },
      { label: 'Get approval before publishing', value: 'approval-before-publish' },
      { label: 'Schedule to go live automatically', value: 'schedule-publish' },
      { label: 'A/B test different versions', value: 'ab-test' },
    ],
  },
  // --- Who Does What? (matrix) ---
  {
    section: 'who-does-what',
    order: 0,
    questionKey: 'who-does-what',
    questionText: 'For each task, indicate who should handle it:',
    inputType: 'matrix',
    options: [
      { label: 'Add new pages', value: 'add-pages' },
      { label: 'Edit existing content', value: 'edit-content' },
      { label: 'Design layout/templates', value: 'design-layout' },
      { label: 'Manage navigation', value: 'manage-nav' },
      { label: 'Set up forms', value: 'set-up-forms' },
      { label: 'Integrate with tools', value: 'integrate-tools' },
      { label: 'Manage SEO settings', value: 'manage-seo' },
      { label: 'Update images/media', value: 'update-media' },
    ],
    columns: [
      { label: 'I handle', value: 'i-handle' },
      { label: 'Developer handles', value: 'developer-handles' },
      { label: 'Either could do', value: 'either' },
      { label: "Don't need this", value: 'dont-need' },
    ],
  },
  // --- Current Platform Assessment ---
  {
    section: 'current-platform',
    order: 0,
    questionKey: 'current-cms-which',
    questionText: "If you're currently using a CMS, which one?",
    inputType: 'text-input',
    required: false,
  },
  {
    section: 'current-platform',
    order: 1,
    questionKey: 'satisfaction-design-flexibility',
    questionText: 'Rate your satisfaction with your current platform: Design flexibility',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: '1', maxLabel: '5' },
    required: false,
  },
  {
    section: 'current-platform',
    order: 2,
    questionKey: 'satisfaction-ease-updates',
    questionText: 'Rate your satisfaction: Ease of updates',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: '1', maxLabel: '5' },
    required: false,
  },
  {
    section: 'current-platform',
    order: 3,
    questionKey: 'satisfaction-integrations',
    questionText: 'Rate your satisfaction: Integration capabilities',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: '1', maxLabel: '5' },
    required: false,
  },
  {
    section: 'current-platform',
    order: 4,
    questionKey: 'satisfaction-marketing',
    questionText: 'Rate your satisfaction: Marketing features',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: '1', maxLabel: '5' },
    required: false,
  },
  {
    section: 'current-platform',
    order: 5,
    questionKey: 'satisfaction-cost-value',
    questionText: 'Rate your satisfaction: Cost vs. value',
    inputType: 'rating-scale',
    ratingMin: 1,
    ratingMax: 5,
    ratingLabels: { minLabel: '1', maxLabel: '5' },
    required: false,
  },
  {
    section: 'current-platform',
    order: 6,
    questionKey: 'love-about-current',
    questionText: 'What do you love about your current platform?',
    inputType: 'text-input',
    required: false,
  },
  {
    section: 'current-platform',
    order: 7,
    questionKey: 'frustrates-about-current',
    questionText: 'What frustrates you most about your current platform?',
    inputType: 'text-input',
    required: false,
  },
  // --- Future State Wishlist ---
  {
    section: 'future-state-wishlist',
    order: 0,
    questionKey: 'wishlist-love-most',
    questionText: '"The thing I\'ll love most about updating the site will be..."',
    inputType: 'text-input',
    required: false,
  },
  {
    section: 'future-state-wishlist',
    order: 1,
    questionKey: 'wishlist-no-longer-wait',
    questionText: '"I\'ll no longer have to wait for..."',
    inputType: 'text-input',
    required: false,
  },
  {
    section: 'future-state-wishlist',
    order: 2,
    questionKey: 'wishlist-finally-able',
    questionText: '"I\'ll finally be able to..."',
    inputType: 'text-input',
    required: false,
  },
  {
    section: 'future-state-wishlist',
    order: 3,
    questionKey: 'wishlist-developer-involved',
    questionText: '"Our developer will only need to get involved when..."',
    inputType: 'text-input',
    required: false,
  },
]
